networks:
  app-network:
    driver: bridge

services:
  nginx:
    image: nginx:alpine
    container_name: web-server
    restart: unless-stopped
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./../:${APP_DIR:-/var/www/html/app}
    links:
      - php-fpm
    ports:
      - "${HOST_PORT:-80}:80"
    networks:
      - app-network

  php-fpm:
    build:
      context: .
      dockerfile: ./php/Dockerfile
      args:
        HOST_TZ: ${HOST_TZ:-UTC}
        WORK_DIR: ${APP_DIR:-/var/www/html/app}
        XDEBUG_INSTALL: ${XDEBUG_INSTALL:-false}
    container_name: php-fpm
    restart: unless-stopped
    user: "${HOST_UID:-1000}:${HOST_GID:-1000}"
    environment:
      TZ: ${HOST_TZ:-UTC}
    volumes:
      - ./../:${APP_DIR:-/var/www/html/app}
    #    depends_on:
    #      - mysql
    extra_hosts:
      - host.docker.internal:host-gateway
    networks:
      - app-network

#  mysql:
#    image: mysql:latest
#    container_name: mysql
#    restart: unless-stopped
#    tty: true
#    # ports:
#    #   - 3306:3306
#    environment:
#      MYSQL_DATABASE: ${DB_DATABASE:-developer}
#      MYSQL_USER: ${DB_USERNAME:-developer}
#      MYSQL_PASSWORD: ${DB_PASSWORD:-secret}
#      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-secret}
#    volumes:
#      - ./data/mysql:/var/lib/mysql
#    networks:
#      - app-network

#  redis:
#    image: redis:alpine
#    container_name: redis
#    restart: unless-stopped
#    # ports:
#    #   - 6379:6379
#    networks:
#      - app-network

#  npm:
#    image: node:22-alpine
#    container_name: npm
#    volumes:
#      - ./src:${APP_DIR:-/var/www/html/app}
#    working_dir: ${APP_DIR:-/var/www/html/app}
#    #entrypoint: [ 'npm' ]
#    networks:
#      - app-network

  mailpit:
    image: axllent/mailpit:latest
    container_name: mailpit
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - app-network
